# Generated by Django 4.1.1 on 2022-09-20 15:45
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Author",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания записи"
            ),
        ),
        migrations.AddField(
            model_name="Author",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время обновления записи"
            ),
        ),
    ]
