# Generated by Django 4.1.1 on 2022-09-20 15:45
from typing import List
import ckeditor_uploader.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: List = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Job",
            name="indepth_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Подробное описание"
            ),
        ),
    ]
