# Generated by Django 4.1.13 on 2024-02-22 13:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_added_job_indepth_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="indepth_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Подробное описание выполненной работы",
                verbose_name="Подробное описание",
            ),
        ),
    ]
